"""Remove zipcode field from requests

Revision ID: 028aa87e4f51
Revises: 549f168d1eaf
Create Date: 2020-09-14 07:08:53.674713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028aa87e4f51'
down_revision = '549f168d1eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_zipcode', table_name='requests')
    op.drop_column('requests', 'zipcode')
    op.drop_column('requests', 'id')
    op.create_primary_key('pk_requests_client_zipcode', 'requests', ['client_id', 'zipcode_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('requests', sa.Column('zipcode', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.create_index('ix_requests_zipcode', 'requests', ['zipcode'], unique=False)
    op.drop_constraint("pk_requests_client_zipcode", "requests", type_="primarykey")
    # ### end Alembic commands ###
