"""Initial migration.

Revision ID: 0329d3d7ea32
Revises: 
Create Date: 2020-09-06 19:40:32.495321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0329d3d7ea32"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zipcode", sa.String(length=5), nullable=False),
        sa.Column("client_identifier", sa.String(length=100), nullable=False),
        sa.Column(
            "client_identifier_type",
            sa.Enum("PHONE_NUMBER", "IP", name="clientidentifiertype"),
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("first_ts", sa.Integer(), nullable=False),
        sa.Column("last_ts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_zipcode_client_identifier_client_identifier_type_index",
        "requests",
        ["zipcode", "client_identifier", "client_identifier_type"],
        unique=True,
    )
    op.create_index(op.f("ix_requests_zipcode"), "requests", ["zipcode"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requests_zipcode"), table_name="requests")
    op.drop_index(
        "_zipcode_client_identifier_client_identifier_type_index", table_name="requests"
    )
    op.drop_table("requests")
    # ### end Alembic commands ###
