"""Update requests table

Revision ID: 16b5e0d25426
Revises: 16035f5c4c4c
Create Date: 2020-09-13 07:13:38.123651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "16b5e0d25426"
down_revision = "16035f5c4c4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("requests", "client_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(
        "_zipcode_client_identifier_client_identifier_type_index", table_name="requests"
    )
    op.drop_column("requests", "client_identifier")
    op.drop_column("requests", "client_identifier_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "client_identifier_type",
            postgresql.ENUM("PHONE_NUMBER", "IP", name="clientidentifiertype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "requests",
        sa.Column(
            "client_identifier",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        "_zipcode_client_identifier_client_identifier_type_index",
        "requests",
        ["zipcode", "client_identifier", "client_identifier_type"],
        unique=True,
    )
    op.alter_column("requests", "client_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
