"""add locale column to client table

Revision ID: 1b01295d68ce
Revises: a61bb2d8e596
Create Date: 2020-10-01 21:58:16.765735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b01295d68ce"
down_revision = "a61bb2d8e596"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("locale", sa.String(), server_default="en", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "locale")
    # ### end Alembic commands ###
