"""Add last pm25 to subscriptions

Revision ID: 1c0739669926
Revises: 028aa87e4f51
Create Date: 2020-09-14 22:35:43.713578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0739669926'
down_revision = '028aa87e4f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_pm25', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_pm25')
    # ### end Alembic commands ###
