"""add messages table

Revision ID: 287da0cb4e31
Revises: 8d53344606e0
Create Date: 2020-09-20 03:05:14.169117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287da0cb4e31'
down_revision = '8d53344606e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='messages_client_id_fkey'),
    sa.PrimaryKeyConstraint('client_id', 'type_code', 'timestamp')
    )
    op.create_index(op.f('ix_messages_type_code'), 'messages', ['type_code'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_type_code'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
