"""add coords to sensors

Revision ID: 28fc973c085a
Revises: 5f3e5ff4f100
Create Date: 2022-02-13 07:04:14.433225

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = "28fc973c085a"
down_revision = "5f3e5ff4f100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensors",
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensors", "coordinates")
    # ### end Alembic commands ###
