"""sensors coords

Revision ID: 52ebfa4125a8
Revises: 5f3e5ff4f100
Create Date: 2021-08-31 00:35:45.265217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = "52ebfa4125a8"
down_revision = "5f3e5ff4f100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensors",
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###

    # Now delete all existing data so that it gets rebuilt correctly
    from airq.models.sensors import Sensor
    from airq.models.relations import SensorZipcodeRelation

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    session.query(SensorZipcodeRelation).delete()
    session.query(Sensor).delete()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensors", "coordinates")
    # ### end Alembic commands ###
