"""Add prefs to client

Revision ID: 56dff538c0a7
Revises: 8527f94dfe70
Create Date: 2020-11-23 05:30:38.181150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56dff538c0a7"
down_revision = "8527f94dfe70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("preferences", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "preferences")
    # ### end Alembic commands ###
