"""Add readings.

Revision ID: 70c51d3c79a3
Revises: 0329d3d7ea32
Create Date: 2020-09-08 04:51:55.709866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70c51d3c79a3"
down_revision = "0329d3d7ea32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reading", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensors")
    # ### end Alembic commands ###
