"""Remove unnecessary zipcode columns

Revision ID: 75913573a161
Revises: 56dff538c0a7
Create Date: 2021-02-13 01:20:05.970177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "75913573a161"
down_revision = "56dff538c0a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zipcodes", "min_sensor_distance")
    op.drop_column("zipcodes", "max_sensor_distance")
    op.drop_column("zipcodes", "num_sensors")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "zipcodes",
        sa.Column(
            "num_sensors",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "zipcodes",
        sa.Column(
            "max_sensor_distance",
            postgresql.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "zipcodes",
        sa.Column(
            "min_sensor_distance",
            postgresql.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
