"""JSON blob of metric data

Revision ID: 8527f94dfe70
Revises: d6f61308fc1c
Create Date: 2020-11-12 02:24:29.610344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8527f94dfe70"
down_revision = "d6f61308fc1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("zipcodes", sa.Column("metrics_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zipcodes", "metrics_data")
    # ### end Alembic commands ###
