"""add created_at to clients table

Revision ID: a61bb2d8e596
Revises: f566ac2b3f9d
Create Date: 2020-09-21 06:13:54.763831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a61bb2d8e596"
down_revision = "f566ac2b3f9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("created_at", sa.TIMESTAMP(timezone=True)))
    op.create_index(
        op.f("ix_clients_created_at"), "clients", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
    conn = op.get_bind()
    import datetime
    import pytz

    conn.execute(
        "UPDATE clients SET created_at=%s WHERE created_at IS NULL",
        datetime.datetime.now(tz=pytz.timezone("America/Los_Angeles")),
    )
    op.alter_column(
        "clients",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_created_at"), table_name="clients")
    op.drop_column("clients", "created_at")
    # ### end Alembic commands ###
