"""Track humidity

Revision ID: bc92ae15a407
Revises: 75913573a161
Create Date: 2021-02-13 10:24:05.835108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc92ae15a407"
down_revision = "75913573a161"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("last_humidity", sa.Float(), nullable=True))
    op.add_column("sensors", sa.Column("humidity", sa.Float(), nullable=True))
    op.execute("UPDATE sensors SET humidity = 0")
    op.alter_column("sensors", "humidity", nullable=False)
    op.add_column(
        "zipcodes",
        sa.Column("humidity", sa.Float(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zipcodes", "humidity")
    op.drop_column("sensors", "humidity")
    op.drop_column("clients", "last_humidity")
    # ### end Alembic commands ###
