"""Subscriptions

Revision ID: c3dfa49541af
Revises: b89903c683c5
Create Date: 2020-09-13 23:38:24.527838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3dfa49541af"
down_revision = "b89903c683c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("zipcode_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("disabled_at", sa.Integer(), nullable=False),
        sa.Column("last_executed_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="subscription_client_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["zipcode_id"], ["zipcodes.id"], name="subscription_zipcode_id_fkey"
        ),
        sa.PrimaryKeyConstraint("zipcode_id", "client_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_disabled_at"),
        "subscriptions",
        ["disabled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_last_executed_at"),
        "subscriptions",
        ["last_executed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_last_executed_at"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_disabled_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
