"""Remove requests table

Revision ID: d6f61308fc1c
Revises: 1b01295d68ce
Create Date: 2020-10-14 05:36:26.986157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6f61308fc1c"
down_revision = "1b01295d68ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("first_ts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("last_ts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("zipcode_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="requests_client_id_fk"
        ),
        sa.ForeignKeyConstraint(
            ["zipcode_id"], ["zipcodes.id"], name="requests_zipcode_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "client_id", "zipcode_id", name="pk_requests_client_zipcode"
        ),
    )
    # ### end Alembic commands ###
