"""add events table

Revision ID: f566ac2b3f9d
Revises: 8d53344606e0
Create Date: 2020-09-20 17:44:52.482413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f566ac2b3f9d"
down_revision = "8d53344606e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("type_code", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("json_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name="events_client_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_client_id"), "events", ["client_id"], unique=False)
    op.create_index(op.f("ix_events_timestamp"), "events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_events_type_code"), "events", ["type_code"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_type_code"), table_name="events")
    op.drop_index(op.f("ix_events_timestamp"), table_name="events")
    op.drop_index(op.f("ix_events_client_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
